### ISSUE TITLE
Error in module.json for v2.0.7

### ISSUE THREAD

**Issue by CptnNoFuture** [Maelstrom-Development/wng-dragruler#1]
After the update to v2.0.7 the module can't be updated/intstalled anymore. There seems to be a typo in the module.json.

The url in module.json is:
https://github.com/Maelstrom-Development/wng-dragruler/releases/download/v2.0.7/wng-dragruler-v2.0.7.zip

The actual working link from "releases" is:
https://github.com/Maelstrom-Development/wng-dragruler/releases/download/v2.0.7/wng-dragruler-v2.07.zip

(wng-dragruler-v2.0.7.zip <-> wng-dragruler-v2.07.zip)

**Comment by jmhysong** [comment]
I've fixed the zip filename in v2.0.7. Thank you CptnNoFuture!
